#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : glances
Version  : 3.1.0
Release  : 25
URL      : https://github.com/nicolargo/glances/archive/v3.1.0.tar.gz
Source0  : https://github.com/nicolargo/glances/archive/v3.1.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : LGPL-3.0
Requires: glances-bin = %{version}-%{release}
Requires: glances-license = %{version}-%{release}
Requires: glances-man = %{version}-%{release}
Requires: glances-python = %{version}-%{release}
Requires: glances-python3 = %{version}-%{release}
Requires: psutil
BuildRequires : buildreq-distutils3
BuildRequires : pluggy
BuildRequires : psutil
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : tox
BuildRequires : virtualenv

%description
===============================
Glances - An eye on your system
===============================

%package bin
Summary: bin components for the glances package.
Group: Binaries
Requires: glances-license = %{version}-%{release}

%description bin
bin components for the glances package.


%package doc
Summary: doc components for the glances package.
Group: Documentation
Requires: glances-man = %{version}-%{release}

%description doc
doc components for the glances package.


%package license
Summary: license components for the glances package.
Group: Default

%description license
license components for the glances package.


%package man
Summary: man components for the glances package.
Group: Default

%description man
man components for the glances package.


%package python
Summary: python components for the glances package.
Group: Default
Requires: glances-python3 = %{version}-%{release}

%description python
python components for the glances package.


%package python3
Summary: python3 components for the glances package.
Group: Default
Requires: python3-core

%description python3
python3 components for the glances package.


%prep
%setup -q -n glances-3.1.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1571758728
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
PYTHONPATH=%{buildroot}/usr/lib/python3.7/site-packages python3 setup.py test
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/glances
cp %{_builddir}/glances-3.1.0/COPYING %{buildroot}/usr/share/package-licenses/glances/49d4c0ce1a16601f1e265d446b6c5ea6b512f27c
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/glances

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/glances/*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/glances/49d4c0ce1a16601f1e265d446b6c5ea6b512f27c

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/glances.1

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
